### ISSUE TITLE
Try to add docker container

### ISSUE THREAD

**Issue by Gregcop1** [coopTilleuls/hm-admin#13]

**Comment by gorghoa** [comment]
@todo : add a service API Platform with 3 entities:
- BlogPosting
- Person
- Category

**Comment by Gregcop1** [comment]
Finally, there's no need for Category

**Comment by gorghoa** [comment]
Ok, so here is the plan:
- [x] first: prepare an _api_ service ready to run embedding a pre-configured api-platform with these entities : BlogPosting and Person
- [x] second: prepare a hmadmin service with the dev dependencies required to contributing to hm-admin
- [x] third: write the docker-compose.yml

Objective: Give to the contributor a ready-to-dev offline ready environment

Eventually, the _api_ service would be use as a reference base for testing and ci

**Comment by Gregcop1** [comment]
And of course, update the doc ;) (which is another PR ATM :p)

**Comment by Gregcop1** [comment]
If travis is not compatible with Docker, our e2e tests will have to rely on fixtures (I have a project in mind for this)

**Comment by gorghoa** [comment]
I think travis is ok with docker: https://docs.travis-ci.com/user/docker/ (never tried though…)
