### ISSUE TITLE
hotfix processes: update the contributing guide

### ISSUE THREAD

**Issue by gorghoa** [coopTilleuls/hm-admin#42]
When `twgit hotfix start` is used, twgit fire a new branch, based on the last commit of stable branch. Creating, for instance, a branch named  `hotfix/0.2.3`

Then, when `twgit hotfix finish` is used, twgit merge the hotfix branch into stable, tag it, etc. 

Problem is: When multiple hotfix PR are created in parallel, the async party begins, and a hotfix 0.2.5 could be mergeable before 0.2.3.

So, with hm-admin here is the hotfix process:

```
twgit feature start fix-blablabla
gaa && gc...
g push myfork
...
review
merge
...
twgit hotfix start
twgit feature merge-into-hotfix fix-blablabla
twgit hotfix finish
```

---

ps ironic note: I appreciate github warning me with this message while I’m filling this issue: 

> Please review the guidelines for contributing to this repository.

So now, it’s not just async party time, it’s circular reference party time too! 🎉 🎈 🎂

**Comment by Gregcop1** [comment]
Twgit should stay an intern process. We can accept external contribution which not using it so IMO, we should put that in the contributing file

**Comment by gorghoa** [comment]
I think what you want to say is: “we should **not** put that in the contributing file”.

But ok, I agree, let’s close this issue ;)
